In [1]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv('covid_toy.csv')
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [56]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [57]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(df.drop('has_covid',axis = 1),
                                                       df['has_covid'],
                                                       test_size = 0.2 ,
                                                       random_state = 0)
x_train.head()

    age  gender  fever   cough       city
43   22  Female   99.0    Mild  Bangalore
62   56  Female  104.0  Strong  Bangalore
3    31  Female   98.0    Mild    Kolkata
71   75  Female  104.0  Strong      Delhi
45   72    Male   99.0    Mild  Bangalore

In [18]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories = [['Mild','Strong']])
new_x_train1 = oe.fit_transform(x_train[['cough']])
new_x_test1 = oe.transform(x_test[['cough']])
new_x_train.shape

(80, 1)

In [21]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop = 'first' , dtype = np.int32)
new_x_train2 = ohe.fit_transform(x_train[['gender','city']])
new_x_test2 = ohe.transform(x_test[['gender','city']])
new_x_train2.shape

(80, 4)

In [37]:
from sklearn.impute import SimpleImputer
si = SimpleImputer()
new_x_train3 = si.fit_transform(x_train[['fever']])
new_x_test3 = si.transform(x_test[['fever']])
new_x_train3.shape

(80, 1)

In [42]:
from sklearn.compose import ColumnTransformer
# syntax of ColumnTransformer
# {Variable} = ColumnTransformer(transformers = [
#({nameof diff transformers},{name of function used},{name of fields}),
#({nameof diff transformers},{name of function used},{name of fields}),
#({nameof diff transformers},{name of function used},{name of fields}),]
#, remainder = {name of fields not being processed })

In [52]:
transformer = ColumnTransformer(transformers =[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories = [['Mild' , 'Strong']]),['cough']),
    ('tnf3',OneHotEncoder(drop = ('first')),['gender' , 'city'])
],remainder='passthrough')

In [54]:
transformer.fit_transform(x_train).shape

(80, 7)